apiVersion: v1
kind: Service
metadata:
  name: rails-sample-postgres
spec:
  ports:
    - port: 5432
      protocol: TCP
  selector:
    app: rails-sample-postgres
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rails-sample-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rails-sample-postgres
  template:
    metadata:
      labels:
        app: rails-sample-postgres
    spec:
      containers:
        - name: rails-sample-postgres
          image: postgres
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: rails_sample_development
            - name: POSTGRES_USER
              value: rails_sample
            - name: POSTGRES_PASSWORD
              value: password
